version: '3.9'

services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/opt
    depends_on:
      - db
    networks:
      - my-net
  
  db:
    image: postgres:14.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - my-net
    
volumes:
  db-data:

networks:
  my-net: